- name: datatypes
  hosts: localhost
  vars:
    Course: DevOps with AWS
    Tools:
    - Linux
    - Docker
    - Jenkins
    Experience:
      Devops: 3
      Aws: 2
      Docker: 1
    RealProject: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: 