- name: create ec2 instances
  hosts: local
  connection: local
  vars:
    vpc_subnet_id: subnet-038e95322db78fd17
    sg_id: "sg-07f58d150b8b8711d"
    image_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: kalpanadevops.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records  
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results}}"
  
  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: " {{ zone }} "
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results}}"
    when: item.item == frontend

