- name: variables
  hosts: localhost
  vars:  #variable declaration   # the whole thing till duration is called play level
    Course: "Terraform"
    Trainer: "Sivakumar"
    Duration: "150Hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}}."