- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from {{Trainer}}, Duration is {{Duration}}"

#here no need to mention inventory here separately because ansible will search for it every where.