- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

# here i am not interested to declare any variable so what i am doing is sending arguments in the terminal itself.