- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible') }}" 

- name: uppercase
  hosts: localhost
  vars: 
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    greeting: "Hello, Good Evening"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,3,3,2,4,6,7,8,7]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25,35,67,89]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "minimum age: {{ ages | min }}, maximum age: {{ ages | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary/map/key,value pair
      Course: Ansible
      Trainer: sivakumar
      Duration: 120Hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: After convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"
  

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansible'}
    - {'key': 'Trainer', 'value': 'sivakumar'}
    - {'key': 'Duration', 'value': '120hrs'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: After convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"
  

  - name: check ip address
    vars:
      myip: "356.168.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"



