- name: demo loops
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.debug:
      name: " {{ item }} "
      state: present
    loop:
    - mysql
    - Linux
    - shell
    - ansible

