- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'}  # this whole thing call as item
    - { name: 'postfix', state: 'absent'}
    - { name: 'nginx', state: 'absent'}
