[web]   # group
172.31.84.234   # give remote-node public ip address

[local]
localhost

[mysql]
172.31.27.149

[backend]
172.31.27.147

[servers:children]  # group of groups # servers is group name and children means web,mysql,backend mentioned under this
web
mysql
backend

[all:children] 

[web:vars]
Course=Terraform
Trainer=siva
Duration=60

[localhost:vars]   # Define variables for the 'localhost' group
Course=Ansible
Trainer=Jane
Duration=60