[web]   # group
3.91.208.247   # give remote-node public ip address

[local]
localhost

[mysql]
172.31.27.149

[backend]
172.31.27.147

[all:children]  # group of groups
web
mysql
backend

[web:vars]
Course=Terraform
Trainer=siva
Duration=60

[localhost:vars]   # Define variables for the 'localhost' group
Course=Ansible
Trainer=Jane
Duration=60